# This sets up a Mac OS enviroment on TravisCI and installs and builds the project.

language: objective-c
osx_image: xcode61
rvm:
- 2.1.2

before_install:
  - chmod +x ./Build.sh
  - chmod +x ./Install.sh

install:
- ./Install.sh

script:
- ./Build.sh