# This sets up a Mac OS enviroment on TravisCI and installs and builds the project.

language: objective-c
osx_image: xcode61
rvm:
- 2.1.2

before_install:
  - chmod +x ./Build.sh
  - chmod +x ./Install.sh

install:
- ./Install.sh

script:
- ./Build.sh

after_success:
# We need to update home brew because we're gonna pull down a Mega.co tool with it
- brew update 
# Install the Mega.co C tools from: https://github.com/megous/megatools
- brew install megatools
# Make it runnable
- chmod +x /usr/local/Cellar/megatools/megacopy
- ls
- megacopy -r /Root/ci-build_data -l ./Build/windows/ci-build_data -u unitytravisci@yahoo.com -p TravisUnityCI69 --no-ask-password
